<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_infos.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Conditions générales</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>

<a href='javascript:popup("/extern/msg.php3?p_code=cgv")'><span class="contenu_rouge">Cliquez ici</span></a> pour prendre connaissance de nos conditions générales de vente.
     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>
<br><br>

<?php if ($p_etape==2) { ?>

<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Sécurité Sociale ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>

<strong>Numéro et Clé</strong> : ce numéro est composé de 13 caractères suivis d'une clé de contrôle. Ce numéro est indispensable pour effectuer de façon fiable et rapide l'ouverture des droits du salarié à l'assurance maladie.<br><br>
<strong>Code Grand Régime</strong> : ce numéro est composé de 2 chiffres comme suit : 01 pour un homme; 02 pour une femme ou 03 pour TNS (Travailleur Non Salarié).<br><br>
<strong>Code Caisse</strong> : ce numéro est composé de 3 chiffres - que vous pouvez retrouver sur votre attestation de SS - carte vitale.
     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>
<?php } ?>

<?php if ($p_etape==3) { ?>

<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Date d'effet ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>
Il s'agit de la date à laquelle débutent vos garanties.
     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>
<br>
<br>
<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Modes de paiement ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>
<strong>- CB et prélèvement automatique MENSUEL</strong> : mode de paiement permettant d'avoir le remboursement de vos frais médicaux viré directement sur votre compte bancaire.
<br>
<strong>CB</strong> : système de paiement sécurisé permettant le paiement de la première cotisation mensuelle.
<br>
<strong>Prélèvement automatique</strong> : système de paiement permettant le paiement de votre cotisation mensuelle à date fixe choisie par vous-même.
<br><br>
<strong>- Chèque</strong> : le paiement de votre cotisation, si vous le souhaitez, peut s'effectuer semestriellement ou à l'année. Dans ce cas, vous réglez votre assurance suite à appel à cotisation. Vos remboursements de frais médicaux vous seront regularisés par chèque.
     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>
<br>
<br>
<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> RIB ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>
Pour un mode de paiment mensuel, vous devez renseigner les champs suivant détaillant votre RIB.<br><br>
<strong>Banque</strong> : organisme bancaire auquel vous êtes affiliés.<br><br>
<strong>Guichet</strong> : caisse locale à laquelle vous avez vos comptes clients.<br><br>
<strong>Numéro de compte</strong> : compte sur lequel vous souhaitez être prélevé et toucher vos remboursements.<br><br>
<strong>Clé RIB</strong> : votre identifiant.
     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>

<?php } ?>
