<?php if ($p_etape==1 || $p_etape==4 || $p_etape==5 || $p_etape==6) { ?>

<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Besoin d&rsquo;aide ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>
      Si vous avez besoin d'aide pour votre devis en ligne ou d'informations sur le site, contactez-nous au<br><br>
      <span class="sous_titre"> 03 44 48 21 21</span><br><br>
      ou par le biais de notre formulaire en laissant votre adresse email :<br>
      <br>
      <img src="<?=$g_modulespicturepath?>/devis/picto_mail.gif" width="11" height="7">
      <a href="http://www.assursante.fr/index.dyn.php3?p_idref=12" target="_blanck"><span class="contenu_rouge"><strong>Envoyer un mail</strong></span></a> </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>

<?php } ?>

<?php if ($p_etape==1 || $p_etape==5) { ?>
<br>

<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_infos.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Pratique</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>
      Tout savoir sur les formules Swiss Sant&eacute; :<br><br>
      &bull; <a href="http://www.assursante.fr/index.dyn.php3?p_idref=19" target="_blanck" class="contenu"><strong>Minimale</strong></a><br> &bull; <a href="http://www.assursante.fr/index.dyn.php3?p_idref=20" target="_blanck" class="contenu"><strong>Principale</strong></a><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>
      <img src="<?=$g_modulespicturepath?>/devis/picto_assistance.gif" hspace="2" align="absmiddle"> <a href="http://www.assursante.fr/upload/files/SwissSante_Garanties_assistance.pdf" target="_blanck" class="contenu"><strong>Assistance</strong></a></td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>

<?php } ?>


<?php if ($p_etape==2) { ?>

<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Régime ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>

<strong>S.S.</strong> : Personnes affiliées au régime de la Sécurité Sociale. Les salariés de l'industrie et du commerce sont affiliés au régime général de la Sécurité Sociale.<br><br>
<strong>T.N.S.</strong> : Travailleurs Non Salariés, c'est à dire les professions non salariées non agricoles.<br><br>
<strong>Agricole</strong> : Dans ce régime sont affiliés tous les exploitants agricoles non salariés.

     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>

<?php } ?>

<?php if ($p_etape==3) { ?>

<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Gamme ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>

<strong>économique</strong> : vous protégez votre santé en prenant soin de votre budget grâce à ces trois formules de mutuelle santé complètes et de qualité (minimale - P1 - P2).<br><br>
<strong>principale</strong> : ces formules de mutuelle santé moyen-de-gamme Swiss Life vous offrent des garanties complètes et innovantes avec le remboursement de prestations pour lesquelles la Sécurité Sociale n'intervient pas ainsi que des bonus fidélité (P3-P4-P5).<br><br>
<strong>haut de gamme</strong> : ces formules de mutuelle santé haut-de-gamme Swiss Life vous offrent des garanties sur-mesure avec des remboursements confortables et personnalisés (P6-P7).

     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>
<br>
<table width="150" border="0" cellspacing="0" cellpadding="0" class="contenu">
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_top.gif" width="161" height="6"></td>
 </tr>
 <tr>
  <td background="<?=$g_modulespicturepath?>/devis/focus_pattern.gif"><table width="100%" border="0" cellspacing="0" cellpadding="6" class="contenu">
    <tr>
     <td><img src="<?=$g_modulespicturepath?>/devis/picto_aide.gif" hspace="2" align="absmiddle"><span class="contenu_rouge"><strong> Loi Madelin ?</strong></span><br>
      <img src="<?=$g_modulespicturepath?>/devis/focus_ligne.gif" width="135" height="1" vspace="6"><br>

Concerne uniquement les TNS, loi par laquelle les artisans, commerçants, professions libérales en activité peuvent déduire de leur revenu imposable l'ensemble des cotisations versées au titre d'un contrat de prévoyance complémentaire (mutuelle santé...).

     </td>
    </tr>
  </table></td>
 </tr>
 <tr>
  <td height="6"><img src="<?=$g_modulespicturepath?>/devis/focus_bottom.gif" width="161" height="6"></td>
 </tr>
</table>

<?php } ?>
